{"uid":"8d89d3c1c8f37313","name":"test_decorator_steps","fullName":"tests.test_steps#test_decorator_steps","historyId":"fd62217c3385a97c3b02a331591880c0","time":{"start":1741426760983,"stop":1741426761184,"duration":201},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x556c4592114a <unknown>\n#1 0x556c453beb80 <unknown>\n#2 0x556c453f803f <unknown>\n#3 0x556c453f3d7f <unknown>\n#4 0x556c45444819 <unknown>\n#5 0x556c45443d46 <unknown>\n#6 0x556c45435ca3 <unknown>\n#7 0x556c45401f08 <unknown>\n#8 0x556c45403071 <unknown>\n#9 0x556c458eab5b <unknown>\n#10 0x556c458eeae2 <unknown>\n#11 0x556c458d6967 <unknown>\n#12 0x556c458ef6d4 <unknown>\n#13 0x556c458bac7f <unknown>\n#14 0x556c4590fcd8 <unknown>\n#15 0x556c4590fea9 <unknown>\n#16 0x556c4591ffc6 <unknown>\n#17 0x7f22ffe9caa4 <unknown>\n#18 0x7f22fff29c3c <unknown>","statusTrace":"def test_decorator_steps():\n>    open_main_page()\n\ntests/test_steps.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_steps.py:40: in open_main_page\n    browser.open('https://github.com/')\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/_browser.py:93: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:263: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:178: in get\n    driver = config.driver\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:305: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:129: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:66: in build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:250: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fc87e7b9810>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x556c4591ffc6 \\\\u003Cunknown>\\\\n#17 0x7f22ffe9caa4 \\\\u003Cunknown>\\\\n#18 0x7f22fff29c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x556c4592114a <unknown>\nE       #1 0x556c453beb80 <unknown>\nE       #2 0x556c453f803f <unknown>\nE       #3 0x556c453f3d7f <unknown>\nE       #4 0x556c45444819 <unknown>\nE       #5 0x556c45443d46 <unknown>\nE       #6 0x556c45435ca3 <unknown>\nE       #7 0x556c45401f08 <unknown>\nE       #8 0x556c45403071 <unknown>\nE       #9 0x556c458eab5b <unknown>\nE       #10 0x556c458eeae2 <unknown>\nE       #11 0x556c458d6967 <unknown>\nE       #12 0x556c458ef6d4 <unknown>\nE       #13 0x556c458bac7f <unknown>\nE       #14 0x556c4590fcd8 <unknown>\nE       #15 0x556c4590fea9 <unknown>\nE       #16 0x556c4591ffc6 <unknown>\nE       #17 0x7f22ffe9caa4 <unknown>\nE       #18 0x7f22fff29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x556c4592114a <unknown>\n#1 0x556c453beb80 <unknown>\n#2 0x556c453f803f <unknown>\n#3 0x556c453f3d7f <unknown>\n#4 0x556c45444819 <unknown>\n#5 0x556c45443d46 <unknown>\n#6 0x556c45435ca3 <unknown>\n#7 0x556c45401f08 <unknown>\n#8 0x556c45403071 <unknown>\n#9 0x556c458eab5b <unknown>\n#10 0x556c458eeae2 <unknown>\n#11 0x556c458d6967 <unknown>\n#12 0x556c458ef6d4 <unknown>\n#13 0x556c458bac7f <unknown>\n#14 0x556c4590fcd8 <unknown>\n#15 0x556c4590fea9 <unknown>\n#16 0x556c4591ffc6 <unknown>\n#17 0x7f22ffe9caa4 <unknown>\n#18 0x7f22fff29c3c <unknown>","statusTrace":"def test_decorator_steps():\n>    open_main_page()\n\ntests/test_steps.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_steps.py:40: in open_main_page\n    browser.open('https://github.com/')\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/_browser.py:93: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:263: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:178: in get\n    driver = config.driver\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:305: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:129: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:66: in build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:250: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fc87e7b9810>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x556c4591ffc6 \\\\u003Cunknown>\\\\n#17 0x7f22ffe9caa4 \\\\u003Cunknown>\\\\n#18 0x7f22fff29c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x556c4592114a <unknown>\nE       #1 0x556c453beb80 <unknown>\nE       #2 0x556c453f803f <unknown>\nE       #3 0x556c453f3d7f <unknown>\nE       #4 0x556c45444819 <unknown>\nE       #5 0x556c45443d46 <unknown>\nE       #6 0x556c45435ca3 <unknown>\nE       #7 0x556c45401f08 <unknown>\nE       #8 0x556c45403071 <unknown>\nE       #9 0x556c458eab5b <unknown>\nE       #10 0x556c458eeae2 <unknown>\nE       #11 0x556c458d6967 <unknown>\nE       #12 0x556c458ef6d4 <unknown>\nE       #13 0x556c458bac7f <unknown>\nE       #14 0x556c4590fcd8 <unknown>\nE       #15 0x556c4590fea9 <unknown>\nE       #16 0x556c4591ffc6 <unknown>\nE       #17 0x7f22ffe9caa4 <unknown>\nE       #18 0x7f22fff29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","steps":[{"name":"Открываем главную страницу","time":{"start":1741426760983,"stop":1741426761182,"duration":199},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x556c4592114a <unknown>\n#1 0x556c453beb80 <unknown>\n#2 0x556c453f803f <unknown>\n#3 0x556c453f3d7f <unknown>\n#4 0x556c45444819 <unknown>\n#5 0x556c45443d46 <unknown>\n#6 0x556c45435ca3 <unknown>\n#7 0x556c45401f08 <unknown>\n#8 0x556c45403071 <unknown>\n#9 0x556c458eab5b <unknown>\n#10 0x556c458eeae2 <unknown>\n#11 0x556c458d6967 <unknown>\n#12 0x556c458ef6d4 <unknown>\n#13 0x556c458bac7f <unknown>\n#14 0x556c4590fcd8 <unknown>\n#15 0x556c4590fea9 <unknown>\n#16 0x556c4591ffc6 <unknown>\n#17 0x7f22ffe9caa4 <unknown>\n#18 0x7f22fff29c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/homework_10_allure/homework_10_allure/tests/test_steps.py\", line 40, in open_main_page\n    browser.open('https://github.com/')\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/_browser.py\", line 93, in open\n    self.config._executor.get_url(relative_or_absolute_url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 263, in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 178, in get\n    driver = config.driver\n             ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 305, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 129, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ~~~~~~~~~~~~~~~~~\n    ...<32 lines>...\n        )\n        ~\n    )()\n    ~^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 66, in build_chrome\n    return Chrome(\n        service=config.driver_service or ChromeService(),\n        options=config.driver_options,\n    )\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_steps"},{"name":"host","value":"fv-az1665-585"},{"name":"thread","value":"2400-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_steps"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"1d3d308f5870ad34","reportUrl":"https://hiller994.github.io/homework_10_allure/7//#testresult/1d3d308f5870ad34","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x56068ddde14a <unknown>\n#1 0x56068d87bb80 <unknown>\n#2 0x56068d8b503f <unknown>\n#3 0x56068d8b0d7f <unknown>\n#4 0x56068d901819 <unknown>\n#5 0x56068d900d46 <unknown>\n#6 0x56068d8f2ca3 <unknown>\n#7 0x56068d8bef08 <unknown>\n#8 0x56068d8c0071 <unknown>\n#9 0x56068dda7b5b <unknown>\n#10 0x56068ddabae2 <unknown>\n#11 0x56068dd93967 <unknown>\n#12 0x56068ddac6d4 <unknown>\n#13 0x56068dd77c7f <unknown>\n#14 0x56068ddcccd8 <unknown>\n#15 0x56068ddccea9 <unknown>\n#16 0x56068dddcfc6 <unknown>\n#17 0x7fbc0d89caa4 <unknown>\n#18 0x7fbc0d929c3c <unknown>","time":{"start":1741385570329,"stop":1741385570531,"duration":202}},{"uid":"ebc385e5cdac6c4f","reportUrl":"https://hiller994.github.io/homework_10_allure/6//#testresult/ebc385e5cdac6c4f","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x5631fea4814a <unknown>\n#1 0x5631fe4e5b80 <unknown>\n#2 0x5631fe51f03f <unknown>\n#3 0x5631fe51ad7f <unknown>\n#4 0x5631fe56b819 <unknown>\n#5 0x5631fe56ad46 <unknown>\n#6 0x5631fe55cca3 <unknown>\n#7 0x5631fe528f08 <unknown>\n#8 0x5631fe52a071 <unknown>\n#9 0x5631fea11b5b <unknown>\n#10 0x5631fea15ae2 <unknown>\n#11 0x5631fe9fd967 <unknown>\n#12 0x5631fea166d4 <unknown>\n#13 0x5631fe9e1c7f <unknown>\n#14 0x5631fea36cd8 <unknown>\n#15 0x5631fea36ea9 <unknown>\n#16 0x5631fea46fc6 <unknown>\n#17 0x7f559f69caa4 <unknown>\n#18 0x7f559f729c3c <unknown>","time":{"start":1741385275409,"stop":1741385275613,"duration":204}},{"uid":"b9c469ba574f9783","reportUrl":"https://hiller994.github.io/homework_10_allure/5//#testresult/b9c469ba574f9783","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x560fa410a14a <unknown>\n#1 0x560fa3ba7b80 <unknown>\n#2 0x560fa3be103f <unknown>\n#3 0x560fa3bdcd7f <unknown>\n#4 0x560fa3c2d819 <unknown>\n#5 0x560fa3c2cd46 <unknown>\n#6 0x560fa3c1eca3 <unknown>\n#7 0x560fa3beaf08 <unknown>\n#8 0x560fa3bec071 <unknown>\n#9 0x560fa40d3b5b <unknown>\n#10 0x560fa40d7ae2 <unknown>\n#11 0x560fa40bf967 <unknown>\n#12 0x560fa40d86d4 <unknown>\n#13 0x560fa40a3c7f <unknown>\n#14 0x560fa40f8cd8 <unknown>\n#15 0x560fa40f8ea9 <unknown>\n#16 0x560fa4108fc6 <unknown>\n#17 0x7f578e29caa4 <unknown>\n#18 0x7f578e329c3c <unknown>","time":{"start":1741384536664,"stop":1741384536868,"duration":204}}]},"tags":[]},"source":"8d89d3c1c8f37313.json","parameterValues":[]}